// Данные суворовцев для сайта "Лучшие суворовцы 2025"
const initialData = [
  {
    "callsign": "markiz",
    "password": "rasputin/25",
    "fio": "Администратор системы",
    "platoon": 0,
    "rank": "",
    "fp": 0,
    "avg": 0,
    "birthday": "1970-01-01",
    "position": "Разработчик системы",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "developer"
    ],
    "role": "developer"
  },
  {
    "callsign": "officer",
    "password": "adminsvu25",
    "fio": "Офицер-воспитатель",
    "platoon": 0,
    "rank": "",
    "fp": 0,
    "avg": 0,
    "birthday": "1980-01-01",
    "position": "Модератор системы",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [],
    "role": "moderator"
  },
  {
    "callsign": "star",
    "password": "OPOsyF2t",
    "fio": "Зуенко К.М.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 85,
    "avg": 4.1,
    "birthday": "2007-05-13",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "rocket",
    "password": "VPhLit88",
    "fio": "Катаев В.С.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 98,
    "avg": 4.7,
    "birthday": "2007-12-11",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "eagle",
    "password": "HmUwfZUh",
    "fio": "Сережка А.Д.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 61,
    "avg": 4.2,
    "birthday": "2006-04-20",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "falcon",
    "password": "DED9QGsM",
    "fio": "Трунов Н.С.",
    "platoon": 31,
    "rank": "vserg",
    "fp": 64,
    "avg": 4.5,
    "birthday": "2007-11-12",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": []
  },
  {
    "callsign": "thunder",
    "password": "7vGx40xT",
    "fio": "Ниязов П.С.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 91,
    "avg": 4.8,
    "birthday": "2007-01-05",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "shadow",
    "password": "NzpL8ngj",
    "fio": "Степанко М.И.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 86,
    "avg": 4.8,
    "birthday": "2007-08-11",
    "position": "заместитель командира взвода",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": [
      "zkv"
    ]
  },
  {
    "callsign": "alpha",
    "password": "mAygxGfR",
    "fio": "Ельченко А.Ф.",
    "platoon": 31,
    "rank": "vserg",
    "fp": 91,
    "avg": 4.8,
    "birthday": "2006-02-03",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "bravo",
    "password": "fWVfcAbY",
    "fio": "Агупов С.Д.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 81,
    "avg": 3.6,
    "birthday": "2007-11-02",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "charlie",
    "password": "sHuwHYKb",
    "fio": "Миронов Д.А.",
    "platoon": 31,
    "rank": "vserg",
    "fp": 82,
    "avg": 5.0,
    "birthday": "2007-10-28",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": []
  },
  {
    "callsign": "delta",
    "password": "AGy66vaw",
    "fio": "Мальцев В.А.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 89,
    "avg": 5.0,
    "birthday": "2007-02-17",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "echo",
    "password": "ldJ67PdD",
    "fio": "Майоров Д.Э.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 64,
    "avg": 4.4,
    "birthday": "2006-09-06",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "foxtrot",
    "password": "GyVkgnEX",
    "fio": "Потопов Г.А.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 63,
    "avg": 4.2,
    "birthday": "2006-02-05",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "developer"
    ]
  },
  {
    "callsign": "golf",
    "password": "hjoPdwuA",
    "fio": "Егоров П.Ю.",
    "platoon": 31,
    "rank": "vstarshina",
    "fp": 96,
    "avg": 4.8,
    "birthday": "2007-10-24",
    "position": "старшина курса",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "hotel",
    "password": "T4LBTb3u",
    "fio": "Деденко М.А.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 97,
    "avg": 4.1,
    "birthday": "2007-10-19",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "india",
    "password": "RAt2fpvP",
    "fio": "Горилов М.А.",
    "platoon": 31,
    "rank": "st_vserg",
    "fp": 73,
    "avg": 4.6,
    "birthday": "2007-01-09",
    "position": "старший по группе",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "juliet",
    "password": "MhVizuk1",
    "fio": "Лагутин М.А.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 77,
    "avg": 4.3,
    "birthday": "2006-04-08",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "kilo",
    "password": "rkLMrOdX",
    "fio": "Сериков С.А.",
    "platoon": 31,
    "rank": "ml_vserg",
    "fp": 96,
    "avg": 4.2,
    "birthday": "2007-11-07",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "lima",
    "password": "VGvH0qCk",
    "fio": "Краснов Е.С.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 87,
    "avg": 4.0,
    "birthday": "2007-02-26",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "mike",
    "password": "2U2wPz1c",
    "fio": "Надиров И.К.",
    "platoon": 31,
    "rank": "st_vserg",
    "fp": 88,
    "avg": 3.7,
    "birthday": "2007-03-27",
    "position": "старший по группе",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": []
  },
  {
    "callsign": "november",
    "password": "j6866ckj",
    "fio": "Волошин В.А.",
    "platoon": 31,
    "rank": "suvo",
    "fp": 84,
    "avg": 4.2,
    "birthday": "2006-10-02",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "oscar",
    "password": "6dtsSCZl",
    "fio": "Алексанян А.С.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 81,
    "avg": 3.7,
    "birthday": "2007-03-16",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "papa",
    "password": "NiXaa0Wh",
    "fio": "Бабочкин В.С.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 68,
    "avg": 4.6,
    "birthday": "2006-05-09",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "quebec",
    "password": "TNyy5Gq2",
    "fio": "Рыночкин А.В.",
    "platoon": 32,
    "rank": "ml_vserg",
    "fp": 88,
    "avg": 4.1,
    "birthday": "2007-10-28",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "romeo",
    "password": "kfZhqTtB",
    "fio": "Волков Е.А.",
    "platoon": 32,
    "rank": "vserg",
    "fp": 72,
    "avg": 4.0,
    "birthday": "2006-12-16",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Отличник учебы"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "sierra",
    "password": "jsC1xomN",
    "fio": "Ефремов Е.А.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 81,
    "avg": 4.9,
    "birthday": "2006-04-10",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "tango",
    "password": "HmKLVgF7",
    "fio": "Волченко А.В.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 83,
    "avg": 4.4,
    "birthday": "2006-02-04",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища",
      "Отличник учебы"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "uniform",
    "password": "K0lBjW67",
    "fio": "Горюшкина Н.А.",
    "platoon": 32,
    "rank": "vserg",
    "fp": 60,
    "avg": 4.1,
    "birthday": "2007-01-12",
    "position": "заместитель командира взвода",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "zkv"
    ]
  },
  {
    "callsign": "victor",
    "password": "N6PQHKwH",
    "fio": "Епишкин И.В.",
    "platoon": 32,
    "rank": "ml_vserg",
    "fp": 76,
    "avg": 4.3,
    "birthday": "2006-05-07",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "whiskey",
    "password": "CfG99dsR",
    "fio": "Мякишев О.В.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 95,
    "avg": 4.2,
    "birthday": "2006-01-21",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "xray",
    "password": "lfYt1kOJ",
    "fio": "Михайленко П.П.",
    "platoon": 32,
    "rank": "ml_vserg",
    "fp": 83,
    "avg": 3.7,
    "birthday": "2007-02-19",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "yankee",
    "password": "lyWEBywQ",
    "fio": "Скотинкин А.Р.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 70,
    "avg": 3.7,
    "birthday": "2006-07-13",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "zulu",
    "password": "Tuxtb33G",
    "fio": "Сутягин К.А.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 87,
    "avg": 4.3,
    "birthday": "2006-10-14",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Отличник учебы"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "phoenix",
    "password": "EplQtPvk",
    "fio": "Чертков Е.В.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 61,
    "avg": 4.6,
    "birthday": "2007-06-02",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "dragon",
    "password": "s5JqwzLh",
    "fio": "Синюков А.Д.",
    "platoon": 32,
    "rank": "st_vserg",
    "fp": 93,
    "avg": 4.4,
    "birthday": "2006-07-19",
    "position": "старший по группе",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "wolf",
    "password": "vnRQQWuf",
    "fio": "Шпак Г.Р.",
    "platoon": 32,
    "rank": "vserg",
    "fp": 96,
    "avg": 3.6,
    "birthday": "2006-03-03",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "bear",
    "password": "f4YmBSaM",
    "fio": "Сизиков А.А.",
    "platoon": 32,
    "rank": "vserg",
    "fp": 80,
    "avg": 4.1,
    "birthday": "2007-07-23",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Отличник учебы"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "lion",
    "password": "qu7kcKOi",
    "fio": "Суханов К.А.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 66,
    "avg": 4.7,
    "birthday": "2006-03-01",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "tiger",
    "password": "tszgoFRh",
    "fio": "Чернов Е.А.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 90,
    "avg": 4.8,
    "birthday": "2006-09-15",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "shark",
    "password": "PEDQpzA8",
    "fio": "Ермаков А.Д.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 90,
    "avg": 4.4,
    "birthday": "2007-06-02",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "hawk",
    "password": "nnbs33Vv",
    "fio": "Попов Г.Р.",
    "platoon": 32,
    "rank": "suvo",
    "fp": 87,
    "avg": 4.0,
    "birthday": "2007-03-20",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Отличник учебы"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "raven",
    "password": "9rOkw5MC",
    "fio": "Бородин М.Р.",
    "platoon": 33,
    "rank": "st_vserg",
    "fp": 66,
    "avg": 4.3,
    "birthday": "2006-09-06",
    "position": "старший по группе",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "viper",
    "password": "bZ2e4RQ2",
    "fio": "Бородин А.Р.",
    "platoon": 33,
    "rank": "st_vserg",
    "fp": 79,
    "avg": 4.0,
    "birthday": "2007-08-04",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "cobra",
    "password": "P1RUhyAm",
    "fio": "Дунаева Н.С.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 76,
    "avg": 4.4,
    "birthday": "2006-01-16",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "panther",
    "password": "MZAxYbFv",
    "fio": "Бородин А.А.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 63,
    "avg": 4.0,
    "birthday": "2006-02-27",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": []
  },
  {
    "callsign": "lynx",
    "password": "UaIJg9Ie",
    "fio": "Жажин С.Ю.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 66,
    "avg": 4.0,
    "birthday": "2007-10-05",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "jaguar",
    "password": "VhgUsPUG",
    "fio": "Елистов Н.А.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 77,
    "avg": 4.4,
    "birthday": "2006-10-17",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "leopard",
    "password": "bkzS3ZLn",
    "fio": "Достоевский Е.А.",
    "platoon": 33,
    "rank": "vserg",
    "fp": 63,
    "avg": 3.6,
    "birthday": "2006-01-22",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Отличник учебы"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "cheetah",
    "password": "B7hFbGZP",
    "fio": "Миронов Е.Е.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 85,
    "avg": 4.2,
    "birthday": "2007-05-14",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "puma",
    "password": "Pb18rQpB",
    "fio": "Хлебников И.А.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 60,
    "avg": 4.7,
    "birthday": "2007-03-19",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": []
  },
  {
    "callsign": "mustang",
    "password": "tuFGFpYG",
    "fio": "Тряпкин Р.А.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 73,
    "avg": 3.7,
    "birthday": "2006-06-20",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "stallion",
    "password": "u70VMRmP",
    "fio": "Мурашев Н.М.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 89,
    "avg": 4.6,
    "birthday": "2006-06-09",
    "position": "заместитель командира взвода",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "zkv"
    ]
  },
  {
    "callsign": "bronco",
    "password": "f0ffugij",
    "fio": "Нечаева Г.А.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 64,
    "avg": 4.0,
    "birthday": "2007-03-12",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "maverick",
    "password": "dYHBTfws",
    "fio": "Петухов М.Н.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 74,
    "avg": 4.5,
    "birthday": "2007-03-27",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "ghost",
    "password": "edpho7hy",
    "fio": "Романов Д.А.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 70,
    "avg": 3.9,
    "birthday": "2006-03-11",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "phantom",
    "password": "xD2ctosK",
    "fio": "Суханова К.А.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 66,
    "avg": 3.7,
    "birthday": "2007-01-01",
    "position": "командир отделения",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": [
      "ko"
    ]
  },
  {
    "callsign": "specter",
    "password": "Hv1eAsJx",
    "fio": "Толстикова Т.Р.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 66,
    "avg": 3.7,
    "birthday": "2007-05-26",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "wraith",
    "password": "W2lhxDgm",
    "fio": "Трушникова Е.Ю.",
    "platoon": 33,
    "rank": "suvo",
    "fp": 85,
    "avg": 4.6,
    "birthday": "2007-08-10",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [
      "Порицание за нарушение дисциплины"
    ],
    "badges": []
  },
  {
    "callsign": "banshee",
    "password": "r3wM4uDV",
    "fio": "Холопов К.Н.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 91,
    "avg": 3.6,
    "birthday": "2007-08-22",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "reaper",
    "password": "IkuRzQWt",
    "fio": "Кошкин Н.Р.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 93,
    "avg": 4.0,
    "birthday": "2006-12-27",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "hunter",
    "password": "wCiTzTd6",
    "fio": "Лебедев Р.О.",
    "platoon": 33,
    "rank": "vserg",
    "fp": 62,
    "avg": 4.9,
    "birthday": "2006-11-03",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "sniper",
    "password": "VFbG7rsc",
    "fio": "Старков Г.В.",
    "platoon": 33,
    "rank": "vserg",
    "fp": 67,
    "avg": 4.6,
    "birthday": "2006-11-25",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  },
  {
    "callsign": "warrior",
    "password": "FeVuKlmj",
    "fio": "Симонов Л.М.",
    "platoon": 33,
    "rank": "ml_vserg",
    "fp": 74,
    "avg": 4.1,
    "birthday": "2007-01-21",
    "position": "курсант",
    "avatar": "",
    "banner": "",
    "awards": [
      "Поощрение начальника училища"
    ],
    "penalties": [],
    "badges": []
  }
];
